<template lang="html">
    <div class="nav-wrapper">
        <ul class="nav-content">
            <li v-for="(val,index) in list" :key="index" :class="{'active':index===activeIndex}" @click="changeMenu(index)">
                <a :href="val.menuUrl">
                    <div class="">
                        <p class="chineseName">{{val.ChineseName}}</p>
                        <p class="englishName">{{val.EnglishName}}</p>
                        <i class="icon icon-arrow-left" v-if="val.menuSub.length>0"></i>
                    </div>
                </a>
                <div class="sub-menu" v-show="index===activeIndex">
                    <ul>
                        <li v-for="(menuSubVal,index) in val.menuSub" :key="index" @click="toggleShowMenu(isSubShow,index)" :class="{'is-open':index === secondActiveIndex}">
                            <a href="javascript:;">
                                <img :src="menuSubVal.imgUrl" alt="">
                                <p>
                                    <span>{{menuSubVal.menunamec}}</span><br>
                                    <small>{{menuSubVal.menunamee}}</small>
                                </p>
                                <i class="icon" :class="index === secondActiveIndex ? 'icon-hide' : 'icon-open'"></i>
                            </a>
                            <!-- 过渡效果 -->
                            <transition name="fade" mode="out-in">
                                <!--  v-show="menuSubVal.isSubShow" -->
                                <ul class="clearfixed">
                                    <li v-for="(classificationVal,index) in menuSubVal.classification" :key="index">
                                        <router-link :to="{params:'' }">
                                            <img :src="classificationVal.calssificateUrl" alt="">
                                            <p>{{classificationVal.classificateName}}</p>
                                        </router-link>
                                    </li>
                                </ul>
                            </transition>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
</template>

<script>
export default {
    data(){
        return{
            activeIndex:0,
            secondActiveIndex:'',
            currentUrl:'',
            isSubShow:false,
            iconClass:['icon-open','icon-hide'],
            list:[
                {
                    ChineseName:'双立人',
                    EnglishName:'Zwilling',
                    menuSub:[
                        {
                            imgUrl:"../../../static/header/menu_knife.png",
                            menunamec:"刀具",
                            menunamee:"Knifes",
                            // isSubShow :false,
                            classification:[
                                {
                                    calssificateUrl:'../../../static/header/menu-scd@2x.png',
                                    classificateName:'水果刀'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zpd@2x.png',
                                    classificateName:'中片刀'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-dy@2x.png',
                                    classificateName:'多用刀'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zuhe@2x.png',
                                    classificateName:'热销组合'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-all@2x.png',
                                    classificateName:'查看全部'
                                }
                            ],
                        },
                        {
                            imgUrl:"../../../static/header/menu_pot.png",
                            menunamec:"锅具",
                            menunamee:"Pots",
                            // isSubShow :false,
                            classification:[
                                {
                                    calssificateUrl:'../../../static/header/menu-scd@2x.png',
                                    classificateName:'平底锅'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zpd@2x.png',
                                    classificateName:'炖锅'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-dy@2x.png',
                                    classificateName:'锅具配件'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zuhe@2x.png',
                                    classificateName:'锅具套餐'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-all@2x.png',
                                    classificateName:'查看全部'
                                }
                            ]
                        },
                        {
                            imgUrl:"../../../static/header/menu_Small.png",
                            menunamec:"小家电",
                            menunamee:"Small Appliances",
                            // isSubShow :false,
                            classification:[
                                {
                                    calssificateUrl:'../../../static/header/menu-scd@2x.png',
                                    classificateName:'厨师机'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zpd@2x.png',
                                    classificateName:'料理机'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-dy@2x.png',
                                    classificateName:'搅拌机'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-all@2x.png',
                                    classificateName:'查看全部'
                                }
                            ]
                        },
                        {
                            imgUrl:"../../../static/header/menu_other.png",
                            menunamec:"其他",
                            menunamee:"Others",
                            // isSubShow :false,
                            classification:[
                                {
                                    calssificateUrl:'../../../static/header/menu-scd@2x.png',
                                    classificateName:'炊具'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zpd@2x.png',
                                    classificateName:'西餐具'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-dy@2x.png',
                                    classificateName:'玻璃器皿'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zuhe@2x.png',
                                    classificateName:'美甲产品'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-all@2x.png',
                                    classificateName:'查看全部'
                                }
                            ]
                        },
                    ]
                },
                {
                    ChineseName:'珐宝*',
                    EnglishName:'Staub',
                    menuSub:[
                        {
                            imgUrl:"../../../static/header/menu_knife.png",
                            menunamec:"1刀具",
                            menunamee:"Knifes",
                            // isSubShow :false,
                            classification:[
                                {
                                    calssificateUrl:'../../../static/header/menu-scd@2x.png',
                                    classificateName:'水果刀'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zpd@2x.png',
                                    classificateName:'中片刀'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-dy@2x.png',
                                    classificateName:'多用刀'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zuhe@2x.png',
                                    classificateName:'热销组合'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-all@2x.png',
                                    classificateName:'查看全部'
                                }
                            ]
                        },
                        {
                            imgUrl:"../../../static/header/menu_pot.png",
                            menunamec:"锅具",
                            menunamee:"Pots",
                            // isSubShow :false,
                            classification:[
                                {
                                    calssificateUrl:'../../../static/header/menu-scd@2x.png',
                                    classificateName:'平底锅'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zpd@2x.png',
                                    classificateName:'炖锅'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-dy@2x.png',
                                    classificateName:'锅具配件'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zuhe@2x.png',
                                    classificateName:'锅具套餐'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-all@2x.png',
                                    classificateName:'查看全部'
                                }
                            ]
                        },
                        {
                            imgUrl:"../../../static/header/menu_Small.png",
                            menunamec:"小家电",
                            menunamee:"Small Appliances",
                            // isSubShow :false,
                            classification:[
                                {
                                    calssificateUrl:'../../../static/header/menu-scd@2x.png',
                                    classificateName:'厨师机'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zpd@2x.png',
                                    classificateName:'料理机'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-dy@2x.png',
                                    classificateName:'搅拌机'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-all@2x.png',
                                    classificateName:'查看全部'
                                }
                            ]
                        },
                        {
                            imgUrl:"../../../static/header/menu_other.png",
                            menunamec:"其他",
                            menunamee:"Others",
                            // isSubShow :false,
                            classification:[
                                {
                                    calssificateUrl:'../../../static/header/menu-scd@2x.png',
                                    classificateName:'炊具'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zpd@2x.png',
                                    classificateName:'西餐具'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-dy@2x.png',
                                    classificateName:'玻璃器皿'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zuhe@2x.png',
                                    classificateName:'美甲产品'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-all@2x.png',
                                    classificateName:'查看全部'
                                }
                            ]
                        },
                    ]
                },
                {
                    ChineseName:'巴拉利尼',
                    EnglishName:'Ballarini',
                    menuSub:[
                        {
                            imgUrl:"../../../static/header/menu_knife.png",
                            menunamec:"2刀具",
                            menunamee:"Knifes",
                            // isSubShow :false,
                            classification:[
                                {
                                    calssificateUrl:'../../../static/header/menu-scd@2x.png',
                                    classificateName:'水果刀'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zpd@2x.png',
                                    classificateName:'中片刀'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-dy@2x.png',
                                    classificateName:'多用刀'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zuhe@2x.png',
                                    classificateName:'热销组合'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-all@2x.png',
                                    classificateName:'查看全部'
                                }
                            ]
                        },
                        {
                            imgUrl:"../../../static/header/menu_pot.png",
                            menunamec:"锅具",
                            menunamee:"Pots",
                            // isSubShow :false,
                            classification:[
                                {
                                    calssificateUrl:'../../../static/header/menu-scd@2x.png',
                                    classificateName:'平底锅'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zpd@2x.png',
                                    classificateName:'炖锅'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-dy@2x.png',
                                    classificateName:'锅具配件'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zuhe@2x.png',
                                    classificateName:'锅具套餐'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-all@2x.png',
                                    classificateName:'查看全部'
                                }
                            ]
                        },
                        {
                            imgUrl:"../../../static/header/menu_Small.png",
                            menunamec:"小家电",
                            menunamee:"Small Appliances",
                            // isSubShow :false,
                            classification:[
                                {
                                    calssificateUrl:'../../../static/header/menu-scd@2x.png',
                                    classificateName:'厨师机'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zpd@2x.png',
                                    classificateName:'料理机'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-dy@2x.png',
                                    classificateName:'搅拌机'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-all@2x.png',
                                    classificateName:'查看全部'
                                }
                            ]
                        },
                        {
                            imgUrl:"../../../static/header/menu_other.png",
                            menunamec:"其他",
                            menunamee:"Others",
                            // isSubShow :false,
                            classification:[
                                {
                                    calssificateUrl:'../../../static/header/menu-scd@2x.png',
                                    classificateName:'炊具'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zpd@2x.png',
                                    classificateName:'西餐具'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-dy@2x.png',
                                    classificateName:'玻璃器皿'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zuhe@2x.png',
                                    classificateName:'美甲产品'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-all@2x.png',
                                    classificateName:'查看全部'
                                }
                            ]
                        },
                    ]
                },
                {
                    ChineseName:'热销分类',
                    EnglishName:'Zwilling',
                    menuSub:[
                        {
                            imgUrl:"../../../static/header/menu_knife.png",
                            menunamec:"必备单品",
                            menunamee:"Knifes",
                            // isSubShow :false,
                            classification:[
                                {
                                    calssificateUrl:'../../../static/header/menu-scd@2x.png',
                                    classificateName:'水果刀'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zpd@2x.png',
                                    classificateName:'中片刀'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-dy@2x.png',
                                    classificateName:'多用刀'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zuhe@2x.png',
                                    classificateName:'热销组合'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-all@2x.png',
                                    classificateName:'查看全部'
                                }
                            ]
                        },
                        {
                            imgUrl:"../../../static/header/menu_pot.png",
                            menunamec:"套装精选",
                            menunamee:"Pots",
                            // isSubShow :false,
                            classification:[
                                {
                                    calssificateUrl:'../../../static/header/menu-scd@2x.png',
                                    classificateName:'平底锅'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zpd@2x.png',
                                    classificateName:'炖锅'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-dy@2x.png',
                                    classificateName:'锅具配件'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zuhe@2x.png',
                                    classificateName:'锅具套餐'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-all@2x.png',
                                    classificateName:'查看全部'
                                }
                            ]
                        },
                        {
                            imgUrl:"../../../static/header/menu_Small.png",
                            menunamec:"礼意之选",
                            menunamee:"Small Appliances",
                            // isSubShow :false,
                            classification:[
                                {
                                    calssificateUrl:'../../../static/header/menu-scd@2x.png',
                                    classificateName:'厨师机'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zpd@2x.png',
                                    classificateName:'料理机'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-dy@2x.png',
                                    classificateName:'搅拌机'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-all@2x.png',
                                    classificateName:'查看全部'
                                }
                            ]
                        },
                        {
                            imgUrl:"../../../static/header/menu_other.png",
                            menunamec:"销售榜单",
                            menunamee:"Others",
                            // isSubShow :false,
                            classification:[
                                {
                                    calssificateUrl:'../../../static/header/menu-scd@2x.png',
                                    classificateName:'炊具'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zpd@2x.png',
                                    classificateName:'西餐具'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-dy@2x.png',
                                    classificateName:'玻璃器皿'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zuhe@2x.png',
                                    classificateName:'美甲产品'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-all@2x.png',
                                    classificateName:'查看全部'
                                }
                            ]
                        },
                    ]
                },
                {
                    ChineseName:'双立人活动',
                    EnglishName:'Zwilling',
                    menuSub:[
                        {
                            imgUrl:"../../../static/header/menu_knife.png",
                            menunamec:"美食学院",
                            menunamee:"Knifes",
                            // isSubShow :false,
                            classification:[
                                {
                                    calssificateUrl:'../../../static/header/menu-scd@2x.png',
                                    classificateName:'水果刀'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zpd@2x.png',
                                    classificateName:'中片刀'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-dy@2x.png',
                                    classificateName:'多用刀'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zuhe@2x.png',
                                    classificateName:'热销组合'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-all@2x.png',
                                    classificateName:'查看全部'
                                }
                            ]
                        },
                        {
                            imgUrl:"../../../static/header/menu_pot.png",
                            menunamec:"菜谱分享",
                            menunamee:"Pots",
                            // isSubShow :false,
                            classification:[
                                {
                                    calssificateUrl:'../../../static/header/menu-scd@2x.png',
                                    classificateName:'平底锅'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zpd@2x.png',
                                    classificateName:'炖锅'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-dy@2x.png',
                                    classificateName:'锅具配件'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zuhe@2x.png',
                                    classificateName:'锅具套餐'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-all@2x.png',
                                    classificateName:'查看全部'
                                }
                            ]
                        },
                        {
                            imgUrl:"../../../static/header/menu_Small.png",
                            menunamec:"视频专区",
                            menunamee:"Small Appliances",
                            // isSubShow :false,
                            classification:[
                                {
                                    calssificateUrl:'../../../static/header/menu-scd@2x.png',
                                    classificateName:'厨师机'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zpd@2x.png',
                                    classificateName:'料理机'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-dy@2x.png',
                                    classificateName:'搅拌机'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-all@2x.png',
                                    classificateName:'查看全部'
                                }
                            ]
                        },
                        {
                            imgUrl:"../../../static/header/menu_other.png",
                            menunamec:"其他",
                            menunamee:"Others",
                            // isSubShow :false,
                            classification:[
                                {
                                    calssificateUrl:'../../../static/header/menu-scd@2x.png',
                                    classificateName:'炊具'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zpd@2x.png',
                                    classificateName:'西餐具'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-dy@2x.png',
                                    classificateName:'玻璃器皿'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-zuhe@2x.png',
                                    classificateName:'美甲产品'
                                },
                                {
                                    calssificateUrl:'../../../static/header/menu-all@2x.png',
                                    classificateName:'查看全部'
                                }
                            ]
                        },
                    ]
                },
                {
                    ChineseName:'双立人故事',
                    EnglishName:'',
                    menuSub:[

                    ],
                    menuUrl: "https://www.baidu.com/"
                },
                {
                    ChineseName:'美食分院',
                    EnglishName:'',
                    menuSub:[
                    ],
                    menuUrl: "https://www.baidu.com/"
                }
            ]
        }
    },
    watch: {
      // '$route'() {
      //   this.currentUrl = this.$route.fullPath; // 实时监测当前路由的变化并且赋值
      // }

    },
    methods:{
        changeMenu(index){
            this.activeIndex = index
        },
        toggleShowMenu(isSubShow,index){
            this.isSubShow = !this.isSubShow;
            this.secondActiveIndex = index
            console.info(this)
        }
    }
}
</script>

<style lang="less">
@import "sideBar.less";
</style>
